(* CSE 341, HW2 Provided Code! *)

(* This is from file json.ml in this directory. json.ml
 * contains the main datatype definition we will use throughout the
 * assignment. You will want to look over this file before starting. *)
include Json

(* These come from the parsed_*_bus.ml.
   Each file binds one variable: small_bus_positions (10 reports),
   medium_bus_positions (100 reports), and complete_bus_positions (~1000 reports),
   respectively with the data that you will need to implement
   your homework.
*)
open Json_structures.Parsed_complete_bus
open Json_structures.Parsed_medium_bus
open Json_structures.Parsed_small_bus

(* provided helper function that deduplicates a list *)
let dedup xs = List.sort_uniq compare xs

(* provided helper function that sorts a given list *)
let sort xs = List.sort compare xs

(* provided helper function to convert a float to a string *)
(* OCaml's string_of_float is not quite RFC compliant due to its tendency
   to output whole numbers with trailing decimal points without a zero.
   But, printf does the job how we want. *)
let json_string_of_float f =
  Printf.sprintf "%g" f
  
(* 1 *)
let make_silly_json i =
  (* Defines a recursive helper function to build the list of JSON objects. *)
  let rec build_list current_i =
    (* If the counter is less than 1, stop recursion. *)
    if current_i < 1 then
      []
    (* For all numbers from i down to 1. *)
    else
      (* Create a single JSON object with fields "n" and "b" as required.*)
      let current_obj = Object [("n", Num (float_of_int current_i)); ("b", True)] in
      (* Prepend the new object to the list generated by the recursive call. *)
      current_obj :: build_list (current_i - 1)
  in
  (* Call the helper function and wrap the resulting list in the Array constructor. *)
  Array (build_list i)

(* 2 *)
let rec concat_with (sep, ss) =
  match ss with
  | [] -> "" (* Base Case *)
  | [x] -> x (* If there's only one string, return it without adding the separator *)
  | x :: xs -> x ^ sep ^ concat_with (sep, xs) (* Add first string and separator, recursively add *)

(* 3 *)
let quote_string s = "\"" ^ s ^ "\"" (* Use string literal for double quote and concatenate with s *)

(* 4 *)
let rec string_of_json j =
  match j with
  | Num f -> json_string_of_float f
  | String s -> quote_string s
  | False -> "false"
  | True -> "true"
  | Null -> "null"
  | Array js ->
      let string_list = List.map string_of_json js in
      "[" ^ concat_with (", ", string_list) ^ "]"
  | Object kvs ->
      (* Helper function to convert one key-value pair to a string *)
      let string_of_pair (k, v) =
        let quoted_key = quote_string k in
        let string_v = string_of_json v in
        quoted_key ^ " : " ^ string_v
      in
      let string_list = List.map string_of_pair kvs in
      "{" ^ concat_with (", ", string_list) ^ "}"

(* 5 *)
let rec take (n,xs) = [] (* TODO *)

(* 6 *)
let rec firsts xs = [] (* TODO *)

(* 7 *)
(* write your comment here *)

(* 8 *)
let rec assoc (k, xs) = None (* TODO *)

(* 9 *)
let dot (j, f) = Some (String "TODO") (* TODO *)

(* 10 *)
let rec dots (j, fs) = Some (String "TODO") (* TODO *)

(* 11 *)
let one_fields j = ["TODO"] (* TODO *)

(* 12 *)
let no_repeats xs = false (* TODO *)

(* 13 *)
let rec recursive_no_field_repeats j = false (* TODO *)

(* 14 *)
let count_occurrences xs = [("TODO", 0)] (* TODO *)

(* 15 *)
let rec string_values_for_access_path (fs, js) = ["TODO"] (* TODO *)

(* 16 *)
let rec filter_access_path_value (fs, v, js) = [Null] (* TODO *)

(* Types for use in problems 17-20. *)
type rect = { min_latitude: float; max_latitude: float;
              min_longitude: float; max_longitude: float }
type point = { latitude: float; longitude: float }

(* 17 *)
let in_rect (r, p) = false (* TODO *)

(* 18 *)
let point_of_json j = Some {latitude = -1.; longitude = -1.} (* TODO *)

(* 19 *)
let rec filter_access_path_in_rect (fs, r, js) = [Null] (* TODO *)

(* 20 *)
(* write your comment here *)

(* For this section, we provide the definition of U district and the functions
 * to calculate a histogram. Use these to create the bindings as requested. 
 * But notice our implementation of histogram uses *your* definition of count_occurrences
 *)
(* The definition of the U district for purposes of this assignment :) *)
let u_district =
  { min_latitude  =  47.648637;
    min_longitude = -122.322099;
    max_latitude  =  47.661176;
    max_longitude = -122.301019
  }

 (* We provide this code commented out because it uses some of your functions 
    that you haven't implemented yet *)

(* Creates a histogram for the given list of strings. 
 * Returns a tuple in which the first element is
 * a string, and the second is the number of times that string
 * is found. *)
let histogram xs = 
  let sorted_xs = List.sort (fun a b -> compare a b) xs in
  let counts = count_occurrences sorted_xs in
  let compare_counts (s1, n1) (s2, n2) =
    if n1 = n2 then compare s1 s2 else compare n1 n2
  in
  List.rev (List.sort compare_counts counts)

let histogram_for_access_path (fs, js) = 
  histogram (string_values_for_access_path (fs,js))

(* notice we use *your* definition of dot *)
let complete_bus_positions_list =
  match (dot (complete_bus_positions, "entity")) with
  | Some (Array xs) -> xs
  | _ -> []

let route_histogram     = [] (* TODO *)
let top_three_routes    = [] (* TODO *)
let buses_in_ud         = [] (* TODO *)
let ud_route_histogram  = [] (* TODO *)
let top_three_ud_routes = [] (* TODO *)
let all_fourty_fours    = [] (* TODO *)
